# Generated by Django 3.2.7 on 2021-10-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.venue'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.activitie'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.venue'),
        ),
        migrations.AddField(
            model_name='institution',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.activitie'),
        ),
        migrations.AddField(
            model_name='institution',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.attendee'),
        ),
        migrations.AddField(
            model_name='institution',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.venue'),
        ),
    ]
