# Generated by Django 3.2.7 on 2021-10-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0002_auto_20211025_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitie',
            name='session_venue',
        ),
    ]
