# Generated by Django 3.2.7 on 2021-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0003_remove_activitie_session_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_coordinates',
            field=models.FloatField(default=0.0),
        ),
    ]
