# Generated by Django 3.2.7 on 2021-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0004_alter_venue_venue_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='session_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='session_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
