# Generated by Django 3.2.7 on 2021-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0005_auto_20211025_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitie',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='activitie',
            name='session_time',
        ),
        migrations.AddField(
            model_name='activitie',
            name='session_when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='session_duration',
            field=models.CharField(default='Not Necessary', max_length=5, null=True),
        ),
    ]
