# Generated by Django 3.2.7 on 2021-10-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0006_auto_20211025_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='session_duration',
            field=models.CharField(default='Not Necessary', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='session_when',
            field=models.DateTimeField(null=True),
        ),
    ]
