# Generated by Django 3.2.7 on 2021-10-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0008_auto_20211026_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='venue',
        ),
    ]
