# Generated by Django 3.2.7 on 2021-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0010_institutionextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='institutionID',
            field=models.CharField(default='xxxx', max_length=20),
        ),
    ]
