# Generated by Django 3.2.7 on 2021-11-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0011_attendee_institutionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='institutionID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
