# Generated by Django 3.2.7 on 2021-11-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0012_alter_attendee_institutionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionextra',
            old_name='institutionID',
            new_name='register_ID',
        ),
    ]
