# Generated by Django 3.2.7 on 2021-11-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0014_attendeeextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='activitie',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RegisterApp.venue'),
        ),
        migrations.DeleteModel(
            name='attendeeExtra',
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='attends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RegisterApp.activitie'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RegisterApp.attendee'),
        ),
    ]
