# Generated by Django 3.2.7 on 2021-11-04 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RegisterApp', '0015_auto_20211104_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institutionExtra',
            new_name='institutionExtra_ID',
        ),
    ]
